[project]
name = "sephora-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "google-adk>=1.12.0",
    "lxml>=6.0.1",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
